#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config top_padding 6
yabai -m config bottom_padding 9
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10
yabai -m config external_bar all:55:0

# optional: focus follows mouse
yabai -m config focus_follows_mouse autofocus

# hold opt + left click -> move window
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move

# hold opt + right click -> resize window
yabai -m config mouse_action2 resize

yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five
yabai -m space 6 --label six

borders active_color=0xff484848 inactive_color=0x00000000 width=5.0
